### PR TITLE
Update rails to 7.0.4.1, Ruby to 3.2.0, and other gems

### PR DESCRIPTION
**Pull request by dmitryrck**
I tested on heroku and it seems to be working :v:

### CODE REVIEW

**Comment by dmitryrck** [comment]
CI fixed 🎉

**Comment by rafaelrpbelo** [comment]
I got something weird on my end:

```sh
~/app/dmitryrck/organize2 (update-ruby-rails-and-gems)$ dkcp run --rm web bundle install
[+] Running 1/0
 ⠿ Container organize2-db-1  Running                                                                                                                                                                                                                                                                                                                                  0.0s
+ exec bundle exec bundle install
Could not find rails-7.0.4.1, listen-3.8.0, oj-3.13.23, pg-1.4.5, puma-6.0.2, codeclimate-test-reporter-1.0.9, actioncable-7.0.4.1, actionmailbox-7.0.4.1, actionmailer-7.0.4.1, actionpack-7.0.4.1, actiontext-7.0.4.1, actionview-7.0.4.1, activejob-7.0.4.1, activemodel-7.0.4.1, activerecord-7.0.4.1, activestorage-7.0.4.1, activesupport-7.0.4.1, railties-7.0.4.1, nio4r-2.5.8, nokogiri-1.14.0, rspec-expectations-3.12.2, rspec-mocks-3.12.3, rack-2.2.6.2, simplecov-0.13.0, bcrypt-3.1.18, websocket-driver-0.7.5, mail-2.8.0.1, globalid-1.0.1, minitest-5.17.0, ffi-1.15.5, mini_portile2-2.8.1, racc-1.6.2, docile-1.1.5, simplecov-html-0.10.2, date-3.3.3 in locally installed gems
Run `bundle install` to install missing gems.
```

:thinking:

**Comment by rafaelrpbelo** [comment]
Nevermind. It's working fine! :sweat_smile:

**Review by rafaelrpbelo — APPROVED** [review]
:rocket:

**Comment by dmitryrck** [comment]
🚀 🎉 Thanks!

**Pull request merged**
